package edu.gatech.chai.VRDR.model;

// DO NOT EDIT MANUALLY! This file was generated by the script "tools/generate_url_Strings_from_VRDR_IG.rb"

import org.hl7.fhir.r4.model.CanonicalType;

public class URL {

    /// <summary>Profile URLs</summary>
    public static class ProfileURL {
        /// <summary>URL for DeathDate</summary>
        public static final CanonicalType DeathDate = new CanonicalType("http://hl7.org/fhir/us/vrdr/StructureDefinition/vrdr-death-date");

        /// <summary>URL for BirthRecordIdentifier</summary>
        public static final CanonicalType BirthRecordIdentifier = new CanonicalType("http://hl7.org/fhir/us/vrdr/StructureDefinition/vrdr-birth-record-identifier");

        /// <summary>URL for DecedentMilitaryService</summary>
        public static final CanonicalType DecedentMilitaryService = new CanonicalType("http://hl7.org/fhir/us/vrdr/StructureDefinition/vrdr-decedent-military-service");

        /// <summary>URL for TobaccoUseContributedToDeath</summary>
        public static final CanonicalType TobaccoUseContributedToDeath = new CanonicalType("http://hl7.org/fhir/us/vrdr/StructureDefinition/vrdr-tobacco-use-contributed-to-death");

        /// <summary>URL for DecedentAge</summary>
        public static final CanonicalType DecedentAge = new CanonicalType("http://hl7.org/fhir/us/vrdr/StructureDefinition/vrdr-decedent-age");

        /// <summary>URL for MannerOfDeath</summary>
        public static final CanonicalType MannerOfDeath = new CanonicalType("http://hl7.org/fhir/us/vrdr/StructureDefinition/vrdr-manner-of-death");

        /// <summary>URL for InputRaceAndEthnicity</summary>
        public static final CanonicalType InputRaceAndEthnicity = new CanonicalType("http://hl7.org/fhir/us/vrdr/StructureDefinition/vrdr-input-race-and-ethnicity");

        /// <summary>URL for CauseOfDeathPart2</summary>
        public static final CanonicalType CauseOfDeathPart2 = new CanonicalType("http://hl7.org/fhir/us/vrdr/StructureDefinition/vrdr-cause-of-death-part2");

        /// <summary>URL for DecedentFather</summary>
        public static final CanonicalType DecedentFather = new CanonicalType("http://hl7.org/fhir/us/vrdr/StructureDefinition/vrdr-decedent-father");

        /// <summary>URL for DecedentEducationLevel</summary>
        public static final CanonicalType DecedentEducationLevel = new CanonicalType("http://hl7.org/fhir/us/vrdr/StructureDefinition/vrdr-decedent-education-level");

        /// <summary>URL for SurgeryDate</summary>
        public static final CanonicalType SurgeryDate = new CanonicalType("http://hl7.org/fhir/us/vrdr/StructureDefinition/vrdr-surgery-date");

        /// <summary>URL for EmergingIssues</summary>
        public static final CanonicalType EmergingIssues = new CanonicalType("http://hl7.org/fhir/us/vrdr/StructureDefinition/vrdr-emerging-issues");

        /// <summary>URL for ExaminerContacted</summary>
        public static final CanonicalType ExaminerContacted = new CanonicalType("http://hl7.org/fhir/us/vrdr/StructureDefinition/vrdr-examiner-contacted");

        /// <summary>URL for CodingStatusValues</summary>
        public static final CanonicalType CodingStatusValues = new CanonicalType("http://hl7.org/fhir/us/vrdr/StructureDefinition/vrdr-coding-status-values");

        /// <summary>URL for DecedentDispositionMethod</summary>
        public static final CanonicalType DecedentDispositionMethod = new CanonicalType("http://hl7.org/fhir/us/vrdr/StructureDefinition/vrdr-decedent-disposition-method");

        /// <summary>URL for Decedent</summary>
        public static final CanonicalType Decedent = new CanonicalType("http://hl7.org/fhir/us/vrdr/StructureDefinition/vrdr-decedent");

        /// <summary>URL for PlaceOfInjury</summary>
        public static final CanonicalType PlaceOfInjury = new CanonicalType("http://hl7.org/fhir/us/vrdr/StructureDefinition/vrdr-place-of-injury");

        /// <summary>URL for CauseOfDeathCodedContentBundle</summary>
        public static final CanonicalType CauseOfDeathCodedContentBundle = new CanonicalType("http://hl7.org/fhir/us/vrdr/StructureDefinition/vrdr-cause-of-death-coded-bundle");

        /// <summary>URL for EntityAxisCauseOfDeath</summary>
        public static final CanonicalType EntityAxisCauseOfDeath = new CanonicalType("http://hl7.org/fhir/us/vrdr/StructureDefinition/vrdr-entity-axis-cause-of-death");

        /// <summary>URL for DeathLocation</summary>
        public static final CanonicalType DeathLocation = new CanonicalType("http://hl7.org/fhir/us/vrdr/StructureDefinition/vrdr-death-location");

        /// <summary>URL for ManualUnderlyingCauseOfDeath</summary>
        public static final CanonicalType ManualUnderlyingCauseOfDeath = new CanonicalType("http://hl7.org/fhir/us/vrdr/StructureDefinition/vrdr-manual-underlying-cause-of-death");

        /// <summary>URL for FuneralHome</summary>
        public static final CanonicalType FuneralHome = new CanonicalType("http://hl7.org/fhir/us/vrdr/StructureDefinition/vrdr-funeral-home");

        /// <summary>URL for DeathCertificate</summary>
        public static final CanonicalType DeathCertificate = new CanonicalType("http://hl7.org/fhir/us/vrdr/StructureDefinition/vrdr-death-certificate");

        /// <summary>URL for DecedentSpouse</summary>
        public static final CanonicalType DecedentSpouse = new CanonicalType("http://hl7.org/fhir/us/vrdr/StructureDefinition/vrdr-decedent-spouse");

        /// <summary>URL for CauseOfDeathPart1</summary>
        public static final CanonicalType CauseOfDeathPart1 = new CanonicalType("http://hl7.org/fhir/us/vrdr/StructureDefinition/vrdr-cause-of-death-part1");

        /// <summary>URL for DecedentMother</summary>
        public static final CanonicalType DecedentMother = new CanonicalType("http://hl7.org/fhir/us/vrdr/StructureDefinition/vrdr-decedent-mother");

        /// <summary>URL for InjuryIncident</summary>
        public static final CanonicalType InjuryIncident = new CanonicalType("http://hl7.org/fhir/us/vrdr/StructureDefinition/vrdr-injury-incident");

        /// <summary>URL for DeathCertificateDocument</summary>
        public static final CanonicalType DeathCertificateDocument = new CanonicalType("http://hl7.org/fhir/us/vrdr/StructureDefinition/vrdr-death-certificate-document");

        /// <summary>URL for InjuryLocation</summary>
        public static final CanonicalType InjuryLocation = new CanonicalType("http://hl7.org/fhir/us/vrdr/StructureDefinition/vrdr-injury-location");

        /// <summary>URL for DeathCertification</summary>
        public static final CanonicalType DeathCertification = new CanonicalType("http://hl7.org/fhir/us/vrdr/StructureDefinition/vrdr-death-certification");

        /// <summary>URL for AutopsyPerformedIndicator</summary>
        public static final CanonicalType AutopsyPerformedIndicator = new CanonicalType("http://hl7.org/fhir/us/vrdr/StructureDefinition/vrdr-autopsy-performed-indicator");

        /// <summary>URL for CodedRaceAndEthnicity</summary>
        public static final CanonicalType CodedRaceAndEthnicity = new CanonicalType("http://hl7.org/fhir/us/vrdr/StructureDefinition/vrdr-coded-race-and-ethnicity");

        /// <summary>URL for AutomatedUnderlyingCauseOfDeath</summary>
        public static final CanonicalType AutomatedUnderlyingCauseOfDeath = new CanonicalType("http://hl7.org/fhir/us/vrdr/StructureDefinition/vrdr-automated-underlying-cause-of-death");

        /// <summary>URL for DecedentPregnancyStatus</summary>
        public static final CanonicalType DecedentPregnancyStatus = new CanonicalType("http://hl7.org/fhir/us/vrdr/StructureDefinition/vrdr-decedent-pregnancy-status");

        /// <summary>URL for DecedentUsualWork</summary>
        public static final CanonicalType DecedentUsualWork = new CanonicalType("http://hl7.org/fhir/us/vrdr/StructureDefinition/vrdr-decedent-usual-work");

        /// <summary>URL for DemographicCodedContentBundle</summary>
        public static final CanonicalType DemographicCodedContentBundle = new CanonicalType("http://hl7.org/fhir/us/vrdr/StructureDefinition/vrdr-demographic-coded-bundle");

        /// <summary>URL for DispositionLocation</summary>
        public static final CanonicalType DispositionLocation = new CanonicalType("http://hl7.org/fhir/us/vrdr/StructureDefinition/vrdr-disposition-location");

        /// <summary>URL for Certifier</summary>
        public static final CanonicalType Certifier = new CanonicalType("http://hl7.org/fhir/us/vrdr/StructureDefinition/vrdr-certifier");

        /// <summary>URL for ActivityAtTimeOfDeath</summary>
        public static final CanonicalType ActivityAtTimeOfDeath = new CanonicalType("http://hl7.org/fhir/us/vrdr/StructureDefinition/vrdr-activity-at-time-of-death");

        /// <summary>URL for RecordAxisCauseOfDeath</summary>
        public static final CanonicalType RecordAxisCauseOfDeath = new CanonicalType("http://hl7.org/fhir/us/vrdr/StructureDefinition/vrdr-record-axis-cause-of-death");

        /// <summary>URL for MortalityRosterBundle </summary>
        public static final CanonicalType MortalityRosterBundle = new CanonicalType("http://hl7.fhir.org/ig/HL7/vrdr/StructureDefinition-vrdr-mortality-roster-bundle");

    }

    /// <summary>Extension URLs</summary>
    public static class ExtensionURL {
        /// <summary>URL for UnitOrAptNumber</summary>
        public static final String UnitOrAptNumber = "http://hl7.org/fhir/us/vrdr/StructureDefinition/UnitOrAptNumber";

        /// <summary>URL for StreetDesignator</summary>
        public static final String StreetDesignator = "http://hl7.org/fhir/us/vrdr/StructureDefinition/StreetDesignator";

        /// <summary>URL for BypassEditFlag</summary>
        public static final String BypassEditFlag = "http://hl7.org/fhir/us/vrdr/StructureDefinition/BypassEditFlag";

        /// <summary>URL for PartialDateTime</summary>
        public static final String PartialDateTime = "http://hl7.org/fhir/us/vrdr/StructureDefinition/PartialDateTime";

        /// <summary>URL for NVSSSexAtDeath</summary>
        public static final String NVSSSexAtDeath = "http://hl7.org/fhir/us/vrdr/StructureDefinition/NVSS-SexAtDeath";

        /// <summary>URL for DateYear</summary>
        public static final String DateYear = "http://hl7.org/fhir/us/vrdr/StructureDefinition/Date-Year";

        /// <summary>URL for PreDirectional</summary>
        public static final String PreDirectional = "http://hl7.org/fhir/us/vrdr/StructureDefinition/PreDirectional";

        /// <summary>URL for AuxiliaryStateIdentifier1</summary>
        public static final String AuxiliaryStateIdentifier1 = "http://hl7.org/fhir/us/vrdr/StructureDefinition/AuxiliaryStateIdentifier1";

        /// <summary>URL for WithinCityLimitsIndicator</summary>
        public static final String WithinCityLimitsIndicator = "http://hl7.org/fhir/us/vrdr/StructureDefinition/WithinCityLimitsIndicator";

        /// <summary>URL for DistrictCode</summary>
        public static final String DistrictCode = "http://hl7.org/fhir/us/vrdr/StructureDefinition/DistrictCode";

        /// <summary>URL for DateDay</summary>
        public static final String DateDay = "http://hl7.org/fhir/us/vrdr/StructureDefinition/Date-Day";

        /// <summary>URL for PartialDate</summary>
        public static final String PartialDate = "http://hl7.org/fhir/us/vrdr/StructureDefinition/PartialDate";

        /// <summary>URL for SpouseAlive</summary>
        public static final String SpouseAlive = "http://hl7.org/fhir/us/vrdr/StructureDefinition/SpouseAlive";

        /// <summary>URL for FilingFormat</summary>
        public static final String FilingFormat = "http://hl7.org/fhir/us/vrdr/StructureDefinition/FilingFormat";

        /// <summary>URL for DateTime</summary>
        public static final String DateTime = "http://hl7.org/fhir/us/vrdr/StructureDefinition/Date-Time";

        /// <summary>URL for PostDirectional</summary>
        public static final String PostDirectional = "http://hl7.org/fhir/us/vrdr/StructureDefinition/PostDirectional";

        /// <summary>URL for StateSpecificField</summary>
        public static final String StateSpecificField = "http://hl7.org/fhir/us/vrdr/StructureDefinition/StateSpecificField";

        /// <summary>URL for AuxiliaryStateIdentifier2</summary>
        public static final String AuxiliaryStateIdentifier2 = "http://hl7.org/fhir/us/vrdr/StructureDefinition/AuxiliaryStateIdentifier2";

        /// <summary>URL for CityCode</summary>
        public static final String CityCode = "http://hl7.org/fhir/us/vrdr/StructureDefinition/CityCode";

        /// <summary>URL for StreetName</summary>
        public static final String StreetName = "http://hl7.org/fhir/us/vrdr/StructureDefinition/StreetName";

        /// <summary>URL for CertificateNumber</summary>
        public static final String CertificateNumber = "http://hl7.org/fhir/us/vrdr/StructureDefinition/CertificateNumber";

        /// <summary>URL for LocationJurisdictionId</summary>
        public static final String LocationJurisdictionId = "http://hl7.org/fhir/us/vrdr/StructureDefinition/Location-Jurisdiction-Id";

        /// <summary>URL for ReplaceStatus</summary>
        public static final 
        String ReplaceStatus = "http://hl7.org/fhir/us/vrdr/StructureDefinition/ReplaceStatus";

        /// <summary>URL for AliasStatus</summary>
        public static final String AliasStatus = "http://hl7.org/fhir/us/vrdr/StructureDefinition/AliasStatus";

        /// <summary>URL for StreetNumber</summary>
        public static final String StreetNumber = "http://hl7.org/fhir/us/vrdr/StructureDefinition/StreetNumber";

        /// <summary>URL for DateMonth</summary>
        public static final String DateMonth = "http://hl7.org/fhir/us/vrdr/StructureDefinition/Date-Month";

    }

    /// <summary>IG URLs</summary>
    public static class IGURL {
        /// <summary>URL for DeathDate</summary>
        public static final String DeathDate = "http://build.fhir.org/ig/HL7/vrdr/StructureDefinition-vrdr-death-date.html";

        /// <summary>URL for BirthRecordIdentifier</summary>
        public static final String BirthRecordIdentifier = "http://build.fhir.org/ig/HL7/vrdr/StructureDefinition-vrdr-birth-record-identifier.html";

        /// <summary>URL for UnitOrAptNumber</summary>
        public static final String UnitOrAptNumber = "http://build.fhir.org/ig/HL7/vrdr/StructureDefinition-UnitOrAptNumber.html";

        /// <summary>URL for DecedentMilitaryService</summary>
        public static final String DecedentMilitaryService = "http://build.fhir.org/ig/HL7/vrdr/StructureDefinition-vrdr-decedent-military-service.html";

        /// <summary>URL for CauseOfDeathPathway</summary>
        public static final String CauseOfDeathPathway = "http://build.fhir.org/ig/HL7/vrdr/StructureDefinition-vrdr-cause-of-death-pathway.html";

        /// <summary>URL for StreetDesignator</summary>
        public static final String StreetDesignator = "http://build.fhir.org/ig/HL7/vrdr/StructureDefinition-StreetDesignator.html";

        /// <summary>URL for TobaccoUseContributedToDeath</summary>
        public static final String TobaccoUseContributedToDeath = "http://build.fhir.org/ig/HL7/vrdr/StructureDefinition-vrdr-tobacco-use-contributed-to-death.html";

        /// <summary>URL for DecedentAge</summary>
        public static final String DecedentAge = "http://build.fhir.org/ig/HL7/vrdr/StructureDefinition-vrdr-decedent-age.html";

        /// <summary>URL for BypassEditFlag</summary>
        public static final String BypassEditFlag = "http://build.fhir.org/ig/HL7/vrdr/StructureDefinition-BypassEditFlag.html";

        /// <summary>URL for PartialDateTime</summary>
        public static final String PartialDateTime = "http://build.fhir.org/ig/HL7/vrdr/StructureDefinition-PartialDateTime.html";

        /// <summary>URL for NVSSSexAtDeath</summary>
        public static final String NVSSSexAtDeath = "http://build.fhir.org/ig/HL7/vrdr/StructureDefinition-NVSS-SexAtDeath.html";

        /// <summary>URL for MannerOfDeath</summary>
        public static final String MannerOfDeath = "http://build.fhir.org/ig/HL7/vrdr/StructureDefinition-vrdr-manner-of-death.html";

        /// <summary>URL for InputRaceAndEthnicity</summary>
        public static final String InputRaceAndEthnicity = "http://build.fhir.org/ig/HL7/vrdr/StructureDefinition-vrdr-input-race-and-ethnicity.html";

        /// <summary>URL for CauseOfDeathPart2</summary>
        public static final String CauseOfDeathPart2 = "http://build.fhir.org/ig/HL7/vrdr/StructureDefinition-vrdr-cause-of-death-part2.html";

        /// <summary>URL for DateYear</summary>
        public static final String DateYear = "http://build.fhir.org/ig/HL7/vrdr/StructureDefinition-Date-Year.html";

        /// <summary>URL for PreDirectional</summary>
        public static final String PreDirectional = "http://build.fhir.org/ig/HL7/vrdr/StructureDefinition-PreDirectional.html";

        /// <summary>URL for DecedentFather</summary>
        public static final String DecedentFather = "http://build.fhir.org/ig/HL7/vrdr/StructureDefinition-vrdr-decedent-father.html";

        /// <summary>URL for DecedentEducationLevel</summary>
        public static final String DecedentEducationLevel = "http://build.fhir.org/ig/HL7/vrdr/StructureDefinition-vrdr-decedent-education-level.html";

        /// <summary>URL for AuxiliaryStateIdentifier1</summary>
        public static final String AuxiliaryStateIdentifier1 = "http://build.fhir.org/ig/HL7/vrdr/StructureDefinition-AuxiliaryStateIdentifier1.html";

        /// <summary>URL for SurgeryDate</summary>
        public static final 
        String SurgeryDate = "http://build.fhir.org/ig/HL7/vrdr/StructureDefinition-vrdr-surgery-date.html";

        /// <summary>URL for EmergingIssues</summary>
        public static final 
        String EmergingIssues = "http://build.fhir.org/ig/HL7/vrdr/StructureDefinition-vrdr-emerging-issues.html";

        /// <summary>URL for ExaminerContacted</summary>
        public static final String ExaminerContacted = "http://build.fhir.org/ig/HL7/vrdr/StructureDefinition-vrdr-examiner-contacted.html";

        /// <summary>URL for CodingStatusValues</summary>
        public static final String CodingStatusValues = "http://build.fhir.org/ig/HL7/vrdr/StructureDefinition-vrdr-coding-status-values.html";

        /// <summary>URL for WithinCityLimitsIndicator</summary>
        public static final String WithinCityLimitsIndicator = "http://build.fhir.org/ig/HL7/vrdr/StructureDefinition-WithinCityLimitsIndicator.html";

        /// <summary>URL for DecedentDispositionMethod</summary>
        public static final String DecedentDispositionMethod = "http://build.fhir.org/ig/HL7/vrdr/StructureDefinition-vrdr-decedent-disposition-method.html";

        /// <summary>URL for Decedent</summary>
        public static final String Decedent = "http://build.fhir.org/ig/HL7/vrdr/StructureDefinition-vrdr-decedent.html";

        /// <summary>URL for PlaceOfInjury</summary>
        public static final String PlaceOfInjury = "http://build.fhir.org/ig/HL7/vrdr/StructureDefinition-vrdr-place-of-injury.html";

        /// <summary>URL for CauseOfDeathCodedContentBundle</summary>
        public static final String CauseOfDeathCodedContentBundle = "http://build.fhir.org/ig/HL7/vrdr/StructureDefinition-vrdr-cause-of-death-coded-bundle.html";

        /// <summary>URL for DistrictCode</summary>
        public static final String DistrictCode = "http://build.fhir.org/ig/HL7/vrdr/StructureDefinition-DistrictCode.html";

        /// <summary>URL for EntityAxisCauseOfDeath</summary>
        public static final String EntityAxisCauseOfDeath = "http://build.fhir.org/ig/HL7/vrdr/StructureDefinition-vrdr-entity-axis-cause-of-death.html";

        /// <summary>URL for DeathLocation</summary>
        public static final String DeathLocation = "http://build.fhir.org/ig/HL7/vrdr/StructureDefinition-vrdr-death-location.html";

        /// <summary>URL for DateDay</summary>
        public static final String DateDay = "http://build.fhir.org/ig/HL7/vrdr/StructureDefinition-Date-Day.html";

        /// <summary>URL for PartialDate</summary>
        public static final String PartialDate = "http://build.fhir.org/ig/HL7/vrdr/StructureDefinition-PartialDate.html";

        /// <summary>URL for ManualUnderlyingCauseOfDeath</summary>
        public static final String ManualUnderlyingCauseOfDeath = "http://build.fhir.org/ig/HL7/vrdr/StructureDefinition-vrdr-manual-underlying-cause-of-death.html";

        /// <summary>URL for FuneralHome</summary>
        public static final String FuneralHome = "http://build.fhir.org/ig/HL7/vrdr/StructureDefinition-vrdr-funeral-home.html";

        /// <summary>URL for SpouseAlive</summary>
        public static final String SpouseAlive = "http://build.fhir.org/ig/HL7/vrdr/StructureDefinition-SpouseAlive.html";

        /// <summary>URL for DeathCertificate</summary>
        public static final String DeathCertificate = "http://build.fhir.org/ig/HL7/vrdr/StructureDefinition-vrdr-death-certificate.html";

        /// <summary>URL for FilingFormat</summary>
        public static final String FilingFormat = "http://build.fhir.org/ig/HL7/vrdr/StructureDefinition-FilingFormat.html";

        /// <summary>URL for DateTime</summary>
        public static final String DateTime = "http://build.fhir.org/ig/HL7/vrdr/StructureDefinition-Date-Time.html";

        /// <summary>URL for DecedentSpouse</summary>
        public static final String DecedentSpouse = "http://build.fhir.org/ig/HL7/vrdr/StructureDefinition-vrdr-decedent-spouse.html";

        /// <summary>URL for PostDirectional</summary>
        public static final String PostDirectional = "http://build.fhir.org/ig/HL7/vrdr/StructureDefinition-PostDirectional.html";

        /// <summary>URL for CauseOfDeathPart1</summary>
        public static final String CauseOfDeathPart1 = "http://build.fhir.org/ig/HL7/vrdr/StructureDefinition-vrdr-cause-of-death-part1.html";

        /// <summary>URL for DecedentMother</summary>
        public static final String DecedentMother = "http://build.fhir.org/ig/HL7/vrdr/StructureDefinition-vrdr-decedent-mother.html";

        /// <summary>URL for StateSpecificField</summary>
        public static final String StateSpecificField = "http://build.fhir.org/ig/HL7/vrdr/StructureDefinition-StateSpecificField.html";

        /// <summary>URL for AuxiliaryStateIdentifier2</summary>
        public static final String AuxiliaryStateIdentifier2 = "http://build.fhir.org/ig/HL7/vrdr/StructureDefinition-AuxiliaryStateIdentifier2.html";

        /// <summary>URL for CityCode</summary>
        public static final String CityCode = "http://build.fhir.org/ig/HL7/vrdr/StructureDefinition-CityCode.html";

        /// <summary>URL for StreetName</summary>
        public static final String StreetName = "http://build.fhir.org/ig/HL7/vrdr/StructureDefinition-StreetName.html";

        /// <summary>URL for InjuryIncident</summary>
        public static final String InjuryIncident = "http://build.fhir.org/ig/HL7/vrdr/StructureDefinition-vrdr-injury-incident.html";

        /// <summary>URL for DeathCertificateDocument</summary>
        public static final String DeathCertificateDocument = "http://build.fhir.org/ig/HL7/vrdr/StructureDefinition-vrdr-death-certificate-document.html";

        /// <summary>URL for InjuryLocation</summary>
        public static final String InjuryLocation = "http://build.fhir.org/ig/HL7/vrdr/StructureDefinition-vrdr-injury-location.html";

        /// <summary>URL for DeathCertification</summary>
        public static final String DeathCertification = "http://build.fhir.org/ig/HL7/vrdr/StructureDefinition-vrdr-death-certification.html";

        /// <summary>URL for CertificateNumber</summary>
        public static final String CertificateNumber = "http://build.fhir.org/ig/HL7/vrdr/StructureDefinition-CertificateNumber.html";

        /// <summary>URL for LocationJurisdictionId</summary>
        public static final String LocationJurisdictionId = "http://build.fhir.org/ig/HL7/vrdr/StructureDefinition-Location-Jurisdiction-Id.html";

        /// <summary>URL for AutopsyPerformedIndicator</summary>
        public static final String AutopsyPerformedIndicator = "http://build.fhir.org/ig/HL7/vrdr/StructureDefinition-vrdr-autopsy-performed-indicator.html";

        /// <summary>URL for CodedRaceAndEthnicity</summary>
        public static final String CodedRaceAndEthnicity = "http://build.fhir.org/ig/HL7/vrdr/StructureDefinition-vrdr-coded-race-and-ethnicity.html";

        /// <summary>URL for ReplaceStatus</summary>
        public static final String ReplaceStatus = "http://build.fhir.org/ig/HL7/vrdr/StructureDefinition-ReplaceStatus.html";

        /// <summary>URL for AutomatedUnderlyingCauseOfDeath</summary>
        public static final String AutomatedUnderlyingCauseOfDeath = "http://build.fhir.org/ig/HL7/vrdr/StructureDefinition-vrdr-automated-underlying-cause-of-death.html";

        /// <summary>URL for StreetNumber</summary>
        public static final String StreetNumber = "http://build.fhir.org/ig/HL7/vrdr/StructureDefinition-StreetNumber.html";

        /// <summary>URL for DecedentPregnancyStatus</summary>
        public static final String DecedentPregnancyStatus = "http://build.fhir.org/ig/HL7/vrdr/StructureDefinition-vrdr-decedent-pregnancy-status.html";

        /// <summary>URL for DecedentUsualWork</summary>
        public static final String DecedentUsualWork = "http://build.fhir.org/ig/HL7/vrdr/StructureDefinition-vrdr-decedent-usual-work.html";

        /// <summary>URL for DemographicCodedContentBundle</summary>
        public static final String DemographicCodedContentBundle = "http://build.fhir.org/ig/HL7/vrdr/StructureDefinition-vrdr-demographic-coded-bundle.html";

        /// <summary>URL for DispositionLocation</summary>
        public static final String DispositionLocation = "http://build.fhir.org/ig/HL7/vrdr/StructureDefinition-vrdr-disposition-location.html";

        /// <summary>URL for DateMonth</summary>
        public static final String DateMonth = "http://build.fhir.org/ig/HL7/vrdr/StructureDefinition-Date-Month.html";

        /// <summary>URL for Certifier</summary>
        public static final String Certifier = "http://build.fhir.org/ig/HL7/vrdr/StructureDefinition-vrdr-certifier.html";

        /// <summary>URL for ActivityAtTimeOfDeath</summary>
        public static final String ActivityAtTimeOfDeath = "http://build.fhir.org/ig/HL7/vrdr/StructureDefinition-vrdr-activity-at-time-of-death.html";

        /// <summary>URL for RecordAxisCauseOfDeath</summary>
        public static final String RecordAxisCauseOfDeath = "http://build.fhir.org/ig/HL7/vrdr/StructureDefinition-vrdr-record-axis-cause-of-death.html";

        /// <summary>URL for MortalityRosterBundle </summary>
        public static final String MortalityRosterBundle = "http://build.fhir.org/ig/HL7/vrdr/StructureDefinition-vrdr-mortality-roster-bundle.html";
    }

    /// <summary>Profile URLs for non-VRDR Profiles</summary>
    public static class OtherProfileURL
    {
        /// <summary>URL for USCorePractitioner</summary>
        public static final String USCorePractitioner = "http://hl7.org/fhir/us/core/StructureDefinition/us-core-practitioner";
    }

    /// <summary>Extension URLs for non-VRDR Profiles</summary>
    public static class OtherExtensionURL
    {
        /// <summary>URL for DataAbsentReason</summary>
        public static final String DataAbsentReason = "http://hl7.org/fhir/StructureDefinition/data-absent-reason";

        /// <summary>URL for PatientBirthPlace</summary>
        public static final String PatientBirthPlace = "http://hl7.org/fhir/StructureDefinition/patient-birthPlace";

        /// <summary>URL for US Core Birthsex </summary>
        public static final String BirthSex = "http://hl7.org/fhir/us/core/StructureDefinition/us-core-birthsex";
    }

    /// <summary>IG URLs for non-VRDR Profiles</summary>
    public static class OtherIGURL
    {
        /// <summary>URL for USCorePractitioner</summary>
        public static final String USCorePractitioner = "http://hl7.org/fhir/us/core/STU4/StructureDefinition-us-core-practitioner.html";
    }

}
